function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // obj_playerMain
	global.__objectDepths[1] = 0; // obj_block
	global.__objectDepths[2] = 0; // obj_tailsJumpMask
	global.__objectDepths[3] = 0; // obj_tailsSpriteMask
	global.__objectDepths[4] = 0; // obj_STGEntryBall
	global.__objectDepths[5] = 0; // obj_STGEntryTimer_Hill
	global.__objectDepths[6] = 0; // obj_STGEnter_stopper
	global.__objectDepths[7] = -1; // obj_STGEntryText_Hill
	global.__objectDepths[8] = 0; // obj_blockBig
	global.__objectDepths[9] = -25; // obj_hudMain
	global.__objectDepths[10] = -25; // obj_score_controller
	global.__objectDepths[11] = 0; // obj_rings_controller
	global.__objectDepths[12] = -25; // obj_countup_controller
	global.__objectDepths[13] = 1000; // obj_hillBGMain
	global.__objectDepths[14] = 10001; // obj_hillWater
	global.__objectDepths[15] = 999; // obj_hillWaterfallSmall
	global.__objectDepths[16] = 999; // obj_hillWaterfallMid
	global.__objectDepths[17] = 999; // obj_hillWaterfallLarge
	global.__objectDepths[18] = 2; // obj_hillFlowers1
	global.__objectDepths[19] = 2; // obj_hillTree
	global.__objectDepths[20] = 2; // obj_hillFlowersNorm
	global.__objectDepths[21] = 0; // obj_hillMusicStop
	global.__objectDepths[22] = -1; // obj_hillSonicMain
	global.__objectDepths[23] = -1; // obj_hillBunny
	global.__objectDepths[24] = -1; // obj_hillDuck
	global.__objectDepths[25] = 0; // obj_hillSquirrel
	global.__objectDepths[26] = -1; // obj_hillBunnyBehind
	global.__objectDepths[27] = -1000; // obj_static
	global.__objectDepths[28] = 0; // obj_dogeTrigger
	global.__objectDepths[29] = 0; // obj_doge
	global.__objectDepths[30] = 0; // obj_dogeText
	global.__objectDepths[31] = -1000; // obj_staticIncrease
	global.__objectDepths[32] = 0; // obj_timerStaticHill
	global.__objectDepths[33] = 0; // obj_tailsDummy
	global.__objectDepths[34] = 0; // obj_hillTailsEvent
	global.__objectDepths[35] = 3; // obj_sonicTree
	global.__objectDepths[36] = 0; // obj_msgPlay
	global.__objectDepths[37] = 0; // obj_hillMsgTimer
	global.__objectDepths[38] = -1000; // obj_fadeIn
	global.__objectDepths[39] = 2; // obj_hideFire
	global.__objectDepths[40] = -1; // obj_STGEntryText_Hide
	global.__objectDepths[41] = 0; // obj_STGEntryTimer_Hide
	global.__objectDepths[42] = 0; // obj_timerEnterSTG2
	global.__objectDepths[43] = -4; // obj_hideFGFlames
	global.__objectDepths[44] = 0; // obj_hideSonicAppear
	global.__objectDepths[45] = -1000; // obj_sonicFlashTails
	global.__objectDepths[46] = -1000; // obj_staticTransSmall
	global.__objectDepths[47] = -2; // obj_sonicChaseTails
	global.__objectDepths[48] = -1; // obj_tailsCry
	global.__objectDepths[49] = -1; // obj_sonicKill
	global.__objectDepths[50] = -5; // obj_bloodSplatCentral
	global.__objectDepths[51] = 0; // obj_tailsDie
	global.__objectDepths[52] = 0; // obj_msgTooSlow
	global.__objectDepths[53] = 0; // obj_tailsDieTimer
	global.__objectDepths[54] = 0; // obj_knuxSpriteMask
	global.__objectDepths[55] = 0; // obj_knuxJumpMask
	global.__objectDepths[56] = -1; // obj_STGEntryText_YCR
	global.__objectDepths[57] = 0; // obj_STGEntryTimer_YCR
	global.__objectDepths[58] = 3; // obj_bloodPipe
	global.__objectDepths[59] = 0; // obj_staticTrigger1
	global.__objectDepths[60] = 0; // obj_staticTrigger2
	global.__objectDepths[61] = 0; // obj_staticTrigger3
	global.__objectDepths[62] = 1; // obj_ycrBloodStain1
	global.__objectDepths[63] = 0; // obj_sonicAppearKnux
	global.__objectDepths[64] = 0; // obj_knuxScared
	global.__objectDepths[65] = -999; // obj_foundYou
	global.__objectDepths[66] = 0; // obj_ycrColliders
	global.__objectDepths[67] = 0; // obj_sonicSmokeLeft
	global.__objectDepths[68] = 0; // obj_sonicSmokeRight
	global.__objectDepths[69] = 0; // obj_knuxCry
	global.__objectDepths[70] = 0; // obj_sonicSmirk1
	global.__objectDepths[71] = 0; // obj_ycrTimer
	global.__objectDepths[72] = 0; // obj_sonicAppearKnuxAni
	global.__objectDepths[73] = -1; // obj_sonicLungeKnux
	global.__objectDepths[74] = 0; // obj_knuxDeath
	global.__objectDepths[75] = -2; // obj_knuxBlood
	global.__objectDepths[76] = 0; // obj_msgSouls
	global.__objectDepths[77] = 0; // obj_knuxDieTimer
	global.__objectDepths[78] = 0; // obj_robotnikSpriteMask
	global.__objectDepths[79] = -1; // obj_STGEntryText_robotnik
	global.__objectDepths[80] = 0; // obj_STGEntryTimer_robotnik
	global.__objectDepths[81] = 0; // obj_robotnikBGTrigger2
	global.__objectDepths[82] = 0; // obj_robotnikBGTrigger3
	global.__objectDepths[83] = 6; // obj_torch
	global.__objectDepths[84] = 0; // obj_robotnikSonicTrigger
	global.__objectDepths[85] = 0; // obj_IAMGOD
	global.__objectDepths[86] = 0; // obj_robotnikLast
	global.__objectDepths[87] = 0; // obj_round2
	global.__objectDepths[88] = -800; // obj_gameOverText
	global.__objectDepths[89] = -26; // obj_hudIcon
	global.__objectDepths[90] = 0; // obj_select1
	global.__objectDepths[91] = -1; // obj_selectStatic
	global.__objectDepths[92] = 0; // obj_selectCursor
	global.__objectDepths[93] = 0; // obj_hillLoader
	global.__objectDepths[94] = 0; // obj_ycrLoader
	global.__objectDepths[95] = 0; // obj_robotnikLoading
	global.__objectDepths[96] = 0; // obj_startup
	global.__objectDepths[97] = -25; // obj_titleBorder
	global.__objectDepths[98] = -10; // obj_titleMain
	global.__objectDepths[99] = -15; // obj_titleFG
	global.__objectDepths[100] = -11; // obj_titleSonic
	global.__objectDepths[101] = -11; // obj_titleSonic2
	global.__objectDepths[102] = -9999; // obj_title666
	global.__objectDepths[103] = 0; // obj_colHiddenEntry
	global.__objectDepths[104] = 0; // obj_knuxGlitch
	global.__objectDepths[105] = 0; // obj_hiddenEnterTimer1
	global.__objectDepths[106] = 0; // obj_msgRules
	global.__objectDepths[107] = 0; // obj_hiddenEnterTimer2
	global.__objectDepths[108] = -1; // obj_STGEntryText_FFFFFF
	global.__objectDepths[109] = 0; // obj_STGEntryTimer_ffffff
	global.__objectDepths[110] = 0; // obj_hiddenFloor1
	global.__objectDepths[111] = 0; // obj_hiddenBGScaler
	global.__objectDepths[112] = -999; // obj_hiddenYoureNext
	global.__objectDepths[113] = 0; // obj_hidden1EndTrigger
	global.__objectDepths[114] = 0; // obj_robotnikTriggerHidden2
	global.__objectDepths[115] = 0; // obj_hidden2Portal
	global.__objectDepths[116] = 0; // obj_hidden2SonicLaugh
	global.__objectDepths[117] = -999; // obj_hidden2PaletteHandler
	global.__objectDepths[118] = 0; // obj_hidden2Floor
	global.__objectDepths[119] = -999; // obj_messageEndgame1
	global.__objectDepths[120] = 0; // obj_hidden2EndTrigger
	global.__objectDepths[121] = 0; // obj_huh
	global.__objectDepths[122] = 0; // obj_nospam
	global.__objectDepths[123] = 0; // obj_fullscreen
	global.__objectDepths[124] = 0; // obj_message
	global.__objectDepths[125] = 0; // obj_skip
	global.__objectDepths[126] = 0; // obj_skip2


	global.__objectNames[0] = "obj_playerMain";
	global.__objectNames[1] = "obj_block";
	global.__objectNames[2] = "obj_tailsJumpMask";
	global.__objectNames[3] = "obj_tailsSpriteMask";
	global.__objectNames[4] = "obj_STGEntryBall";
	global.__objectNames[5] = "obj_STGEntryTimer_Hill";
	global.__objectNames[6] = "obj_STGEnter_stopper";
	global.__objectNames[7] = "obj_STGEntryText_Hill";
	global.__objectNames[8] = "obj_blockBig";
	global.__objectNames[9] = "obj_hudMain";
	global.__objectNames[10] = "obj_score_controller";
	global.__objectNames[11] = "obj_rings_controller";
	global.__objectNames[12] = "obj_countup_controller";
	global.__objectNames[13] = "obj_hillBGMain";
	global.__objectNames[14] = "obj_hillWater";
	global.__objectNames[15] = "obj_hillWaterfallSmall";
	global.__objectNames[16] = "obj_hillWaterfallMid";
	global.__objectNames[17] = "obj_hillWaterfallLarge";
	global.__objectNames[18] = "obj_hillFlowers1";
	global.__objectNames[19] = "obj_hillTree";
	global.__objectNames[20] = "obj_hillFlowersNorm";
	global.__objectNames[21] = "obj_hillMusicStop";
	global.__objectNames[22] = "obj_hillSonicMain";
	global.__objectNames[23] = "obj_hillBunny";
	global.__objectNames[24] = "obj_hillDuck";
	global.__objectNames[25] = "obj_hillSquirrel";
	global.__objectNames[26] = "obj_hillBunnyBehind";
	global.__objectNames[27] = "obj_static";
	global.__objectNames[28] = "obj_dogeTrigger";
	global.__objectNames[29] = "obj_doge";
	global.__objectNames[30] = "obj_dogeText";
	global.__objectNames[31] = "obj_staticIncrease";
	global.__objectNames[32] = "obj_timerStaticHill";
	global.__objectNames[33] = "obj_tailsDummy";
	global.__objectNames[34] = "obj_hillTailsEvent";
	global.__objectNames[35] = "obj_sonicTree";
	global.__objectNames[36] = "obj_msgPlay";
	global.__objectNames[37] = "obj_hillMsgTimer";
	global.__objectNames[38] = "obj_fadeIn";
	global.__objectNames[39] = "obj_hideFire";
	global.__objectNames[40] = "obj_STGEntryText_Hide";
	global.__objectNames[41] = "obj_STGEntryTimer_Hide";
	global.__objectNames[42] = "obj_timerEnterSTG2";
	global.__objectNames[43] = "obj_hideFGFlames";
	global.__objectNames[44] = "obj_hideSonicAppear";
	global.__objectNames[45] = "obj_sonicFlashTails";
	global.__objectNames[46] = "obj_staticTransSmall";
	global.__objectNames[47] = "obj_sonicChaseTails";
	global.__objectNames[48] = "obj_tailsCry";
	global.__objectNames[49] = "obj_sonicKill";
	global.__objectNames[50] = "obj_bloodSplatCentral";
	global.__objectNames[51] = "obj_tailsDie";
	global.__objectNames[52] = "obj_msgTooSlow";
	global.__objectNames[53] = "obj_tailsDieTimer";
	global.__objectNames[54] = "obj_knuxSpriteMask";
	global.__objectNames[55] = "obj_knuxJumpMask";
	global.__objectNames[56] = "obj_STGEntryText_YCR";
	global.__objectNames[57] = "obj_STGEntryTimer_YCR";
	global.__objectNames[58] = "obj_bloodPipe";
	global.__objectNames[59] = "obj_staticTrigger1";
	global.__objectNames[60] = "obj_staticTrigger2";
	global.__objectNames[61] = "obj_staticTrigger3";
	global.__objectNames[62] = "obj_ycrBloodStain1";
	global.__objectNames[63] = "obj_sonicAppearKnux";
	global.__objectNames[64] = "obj_knuxScared";
	global.__objectNames[65] = "obj_foundYou";
	global.__objectNames[66] = "obj_ycrColliders";
	global.__objectNames[67] = "obj_sonicSmokeLeft";
	global.__objectNames[68] = "obj_sonicSmokeRight";
	global.__objectNames[69] = "obj_knuxCry";
	global.__objectNames[70] = "obj_sonicSmirk1";
	global.__objectNames[71] = "obj_ycrTimer";
	global.__objectNames[72] = "obj_sonicAppearKnuxAni";
	global.__objectNames[73] = "obj_sonicLungeKnux";
	global.__objectNames[74] = "obj_knuxDeath";
	global.__objectNames[75] = "obj_knuxBlood";
	global.__objectNames[76] = "obj_msgSouls";
	global.__objectNames[77] = "obj_knuxDieTimer";
	global.__objectNames[78] = "obj_robotnikSpriteMask";
	global.__objectNames[79] = "obj_STGEntryText_robotnik";
	global.__objectNames[80] = "obj_STGEntryTimer_robotnik";
	global.__objectNames[81] = "obj_robotnikBGTrigger2";
	global.__objectNames[82] = "obj_robotnikBGTrigger3";
	global.__objectNames[83] = "obj_torch";
	global.__objectNames[84] = "obj_robotnikSonicTrigger";
	global.__objectNames[85] = "obj_IAMGOD";
	global.__objectNames[86] = "obj_robotnikLast";
	global.__objectNames[87] = "obj_round2";
	global.__objectNames[88] = "obj_gameOverText";
	global.__objectNames[89] = "obj_hudIcon";
	global.__objectNames[90] = "obj_select1";
	global.__objectNames[91] = "obj_selectStatic";
	global.__objectNames[92] = "obj_selectCursor";
	global.__objectNames[93] = "obj_hillLoader";
	global.__objectNames[94] = "obj_ycrLoader";
	global.__objectNames[95] = "obj_robotnikLoading";
	global.__objectNames[96] = "obj_startup";
	global.__objectNames[97] = "obj_titleBorder";
	global.__objectNames[98] = "obj_titleMain";
	global.__objectNames[99] = "obj_titleFG";
	global.__objectNames[100] = "obj_titleSonic";
	global.__objectNames[101] = "obj_titleSonic2";
	global.__objectNames[102] = "obj_title666";
	global.__objectNames[103] = "obj_colHiddenEntry";
	global.__objectNames[104] = "obj_knuxGlitch";
	global.__objectNames[105] = "obj_hiddenEnterTimer1";
	global.__objectNames[106] = "obj_msgRules";
	global.__objectNames[107] = "obj_hiddenEnterTimer2";
	global.__objectNames[108] = "obj_STGEntryText_FFFFFF";
	global.__objectNames[109] = "obj_STGEntryTimer_ffffff";
	global.__objectNames[110] = "obj_hiddenFloor1";
	global.__objectNames[111] = "obj_hiddenBGScaler";
	global.__objectNames[112] = "obj_hiddenYoureNext";
	global.__objectNames[113] = "obj_hidden1EndTrigger";
	global.__objectNames[114] = "obj_robotnikTriggerHidden2";
	global.__objectNames[115] = "obj_hidden2Portal";
	global.__objectNames[116] = "obj_hidden2SonicLaugh";
	global.__objectNames[117] = "obj_hidden2PaletteHandler";
	global.__objectNames[118] = "obj_hidden2Floor";
	global.__objectNames[119] = "obj_messageEndgame1";
	global.__objectNames[120] = "obj_hidden2EndTrigger";
	global.__objectNames[121] = "obj_huh";
	global.__objectNames[122] = "obj_nospam";
	global.__objectNames[123] = "obj_fullscreen";
	global.__objectNames[124] = "obj_message";
	global.__objectNames[125] = "obj_skip";
	global.__objectNames[126] = "obj_skip2";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
